services:
  test_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - test_postgres
    env_file:
      - .env
    environment:
      - DB_HOST=${TEST_DB_HOST}
      - DB_PORT=${TEST_DB_PORT}
      - DB_NAME=${TEST_DB_NAME}
      - DB_USER=${TEST_DB_USER}
      - DB_PASS=${TEST_DB_PASS}
    volumes:
      - ./tests:/project/tests
    entrypoint: [ "sh", "entrypoint.test.sh" ]

  test_postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}
